// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package xsltconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import xsltconnector.XsltConnector;

public class ApplyXsltTemplate extends CustomJavaAction<String>
{
	private String XmlInput;
	private String XsltTemplate;

	public ApplyXsltTemplate(IContext context, String XmlInput, String XsltTemplate)
	{
		super(context);
		this.XmlInput = XmlInput;
		this.XsltTemplate = XsltTemplate;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
        XsltConnector connector = new XsltConnector();
        String resultXml = connector.transform(XmlInput, XsltTemplate);
        return resultXml;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ApplyXsltTemplate";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
